databases:
  - name: myapp3
    databaseName: myapp3
    user: myapp3

services:
  - type: web
    name: myapp3
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myapp3
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false